### ISSUE TITLE
Code formatter for G language

### ISSUE THREAD

**Issue by h8liu** [e8vm/e8vm#9]
`gofmt` like code formatter for G language syntax.

**Comment by h8liu** [comment]
I moved the ast printing stuff into a separate package now, and also added several first test cases.

I will add more test cases. Some will fail at first, and you can then make them passing.

**Comment by kcnm** [comment]
I have question on those `Semi`s. Are they always there? Do they suggest a line break for gfmt?

Something I have not expected but discovered is that
1) "var x int" is parsed as a `VarDecls` (without `Semi`) including a `VarDecl` for `x`
2) single-line `i++` is parsed as a `IncStmt` with `Semi`, but when it is used in `for` the `Semi` appears to be `nil`

Are these behaviors intended? At least confuse me a bit.

**Comment by h8liu** [comment]
Yeah, I agree that it is confusing...

My intention was to keep all non-comment tokens in the AST, so I created (optional) slots for the semicolons in the statements and all places that could have a semi following.

Our semicolon insertion mechanism works the same as go language:
https://golang.org/ref/spec#Semicolons

So, to answer your specific questions:
0) semis do not necessarily suggest a line break; format should print almost never print semis explicitly.
1) each VarDecl has its own semi, so a VarDecls only has semi's when it is a group decl (has "(" and ")"), because a semi is required after the ")";
2) IncStmt in "for" init is a short statement, the semi does not belong to the statement but belongs to "for".

maybe it is best to just discard all the statement-separation semis in the ast's... and treat them the same ways as comments...

**Comment by kcnm** [comment]
Okay, based on what you are saying I will simply ignore semi-s.

**Comment by h8liu** [comment]
basic version done, still much to do on line breaking but it is generally working now. so close this issue for now.
